generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Link
    theme:                 deneb
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          link
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [=id, =name,_http,position, _portada]
      filter:  
        display: [link_category_id,http]
      form:    ~
      edit:    ~
      new:     ~
