# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  tiny_mce_simple: |
    width: "400px",
    height: "200px",
    language: "en",
    relative_urls: false,
    convert_urls: false,
    plugins : "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,imagemanager,filemanager",
    theme_advanced_buttons1 : "save,newdocument,separator,bold,italic,underline,strikethrough,separator,justifyleft,justifycenter,justifyright,justifyfull,separator,styleselect,formatselect,fontselect,fontsizeselect",
    theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,separator,search,replace,separator,bullist,numlist,separator,outdent,indent,blockquote,separator,undo,redo,separator,link,unlink,anchor,image,cleanup,help,code,separator,insertdate,inserttime,preview,separator,forecolor,backcolor",
    theme_advanced_buttons3 : "tablecontrols,separator,hr,removeformat,visualaid,separator,sub,sup,separator,charmap,emotions,iespell,media,advhr,separator,print,separator,ltr,rtl,separator,fullscreen",
    theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,separator,styleprops,spellchecker,separator,cite,abbr,acronym,del,ins,attribs,separator,visualchars,nonbreaking,template,blockquote,pagebreak,separator,insertfile,insertimage",
    plugin_preview_width: "500",
    plugin_preview_height: "600",
    fullscreen_new_window: true,
    theme_advanced_resize_horizontal: true,
    paste_auto_cleanup_on_paste: true,
    extended_valid_elements : "iframe[src|width|height|name|align]"   