# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [sortable.css,galery.css,main_background.css]

  javascripts:    [jquery-1.4.3.min.js, jquery-ui-1.8.6.custom.min.js,common.js, /sfDependentSelectPlugin/js/SelectDependiente.min.js,tiny_mce/tiny_mce.js, jquery.tablednd_0_5.js]


  has_layout:     true
  layout:         layout
