generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ProductCategory
    theme:                 deneb
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          product_category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        name:
          label: Nombre
        content:
          label: Descripción
      list:    
        display: [id, =name]
      filter:  
        class: false
      form:    ~
      edit:    ~
      new:     ~
