generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Consumer
    theme:                 deneb
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          consumer
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [id, =name, city, state, email]
      filter:  
        class: false
      form:    ~
      edit:    ~
      new:     ~
