generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Product
    theme:                 deneb
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          product
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [id, =name, product_category, product_subcategory]
        
      
      filter:  
        display: [product_category_id,product_subcategory_id]
      form:    ~
      edit:    ~
      new:     ~
