# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:  
  news_in_home: 5
  post_list: 5
  sfApplyPlugin:
    from:
      email: "info@grupoagrupo.net"
      fullname: "sodepaz"
  sfDoctrineApplyPlugin:
    afterLogin: register/index
  sfApplyPlugin:
    afterLogin: register/index      
  sf_guard_plugin:
    success_signin_url: register/index
    success_signout_url: @homepage
    remember_key_expiration_age:  2592000   # 30 days in seconds
  tiny_mce_simple: |
    width: "400px",
    height: "200px",
    language: "en",
    relative_urls: false,
    convert_urls: false,
    plugins: "preview, paste, advlink",
    theme_advanced_buttons1: "bold, italic, underline, separator, justifyleft, justifycenter, justifyright, justifyfull, separator, outdent, indent, separator",
    theme_advanced_buttons2: "pastetext, pasteword, separator, link, bullist, numlist, separator, undo, redo, selectall, separator, preview, code",
    theme_advanced_buttons3: "",
    plugin_preview_width: "500",
    plugin_preview_height: "600",
    fullscreen_new_window: true,
    theme_advanced_resize_horizontal: true,
    paste_auto_cleanup_on_paste: true,
    extended_valid_elements : "iframe[src|width|height|name|align]"      
  allowed_mime_types:
    uploads: [application/pdf]
  sf_guard_plugin_allow_login_with_email: false
  sfSimpleGoogleSitemap:
    orm:                  Doctrine                   # possible values: auto, Propel, Doctrine, DbFinder. 'auto' is auto detection. Note: case sensitive!
    urls:                                        # define multiple static urls here
      homepage:                                  # just a name
        url:              http://www.grupoagrupo.net    # full URL, e.g.: with http:// prefix
        freq:             daily                  # must be either: always, hourly, daily, weekly, monthly, yearly, never
        priority:         1.0                    # 1.0 is top priority (100%) compared to 0.2 which is less priority (20%)
    models:                                      # define multiple models to generate sitemap from
      model_blog:                               # just a name
        model:            News       # model class name
        module:           news           # name of module for the url to make up the url
        action:           show                   # name of action for the url to make up the url
        routing:          "@blog"           # use routing for the URLs in the sitemap
        params:                                  # parameters for the url
         slug: getSlug       # name : method to get the parameter value
        date:             getDateCreatedAt           # method to get date last updated for the url
        #criteria:                                # criterias to filter the records to include in the sitemap
         # - { column: is_published, method: IsPublished, operator: = , value: 1 }
        order_by: { column: id, method: Id, sort: desc }
        limit:            50                     # limit to the first x number of records
        freq:             daily                  # must be either: always, hourly, daily, weekly, monthly, yearly, never
        priority:         0.5                    # 1.0 is top priority (100%) compared to 0.5 which is less priority (50%)
      model_category_link:                               # just a name
        model:            LinkCategory       # model class name
        module:           link           # name of module for the url to make up the url
        action:           showCategory                   # name of action for the url to make up the url
        routing:          "@showLinkCategory"           # use routing for the URLs in the sitemap
        params:                                  # parameters for the url
         slug: getSlug       # name : method to get the parameter value
        date:             getDateCreatedAt           # method to get date last updated for the url
        #criteria:                                # criterias to filter the records to include in the sitemap
         # - { column: is_published, method: IsPublished, operator: = , value: 1 }
        order_by: { column: id, method: Id, sort: desc }
        limit:            50                     # limit to the first x number of records
        freq:             daily                  # must be either: always, hourly, daily, weekly, monthly, yearly, never
        priority:         0.5                    # 1.0 is top priority (100%) compared to 0.5 which is less priority (50%)
      model_link:                               # just a name
        model:            Link       # model class name
        module:           link           # name of module for the url to make up the url
        action:           showLink                   # name of action for the url to make up the url
        routing:          "@showLink"           # use routing for the URLs in the sitemap
        params:                                  # parameters for the url
         slug: getSlug       # name : method to get the parameter value
        date:             getDateCreatedAt           # method to get date last updated for the url
        #criteria:                                # criterias to filter the records to include in the sitemap
         # - { column: is_published, method: IsPublished, operator: = , value: 1 }
        order_by: { column: id, method: Id, sort: desc }
        limit:            10                     # limit to the first x number of records
        freq:             daily                  # must be either: always, hourly, daily, weekly, monthly, yearly, never
        priority:         0.5                    # 1.0 is top priority (100%) compared to 0.5 which is less priority (50%)  
      model_providers:                               # just a name
        model:            Provider       # model class name
        module:           provider           # name of module for the url to make up the url
        action:           profile                   # name of action for the url to make up the url
        routing:          "@provider_profile"           # use routing for the URLs in the sitemap
        params:                                 # parameters for the url         
         slug: getSlug       # name : method to get the parameter value
        date:             getDateCreatedAt           # method to get date last updated for the url
        #criteria:                                # criterias to filter the records to include in the sitemap
         # - { column: is_published, method: IsPublished, operator: = , value: 1 }
        order_by: { column: id, method: Id, sort: desc }
        limit:            100                    # limit to the first x number of records
        freq:             daily                  # must be either: always, hourly, daily, weekly, monthly, yearly, never
        priority:         0.5                    # 1.0 is top priority (100%) compared to 0.5 which is less priority (50%)   
      model_product:                               # just a name
        model:            ProviderProduct       # model class name
        module:           product           # name of module for the url to make up the url
        action:           show                   # name of action for the url to make up the url
        routing:          "@provider_product"           # use routing for the URLs in the sitemap
        params:                                  # parameters for the url
         provider_slug: getProviderSlug
         provider_product_slug: getSlug       # name : method to get the parameter value         
        date:             getDateCreatedAt           # method to get date last updated for the url
        #criteria:                                # criterias to filter the records to include in the sitemap
         # - { column: is_published, method: IsPublished, operator: = , value: 1 }
        order_by: { column: id, method: Id, sort: desc }
        limit:            100                     # limit to the first x number of records
        freq:             daily                  # must be either: always, hourly, daily, weekly, monthly, yearly, never
        priority:         0.5                    # 1.0 is top priority (100%) compared to 0.5 which is less priority (50%)     
      #model_tags:                                # just a name
#        model:            sfSimpleBlogTag        # model class name
#        module:           sfSimpleBlog           # name of module for the url to make up the url
#        action:           showByTag              # name of action for the url to make up the url
#        routing:          "@something"           # use routing for the URLs in the sitemap
#        params:                                  # parameters for the url
#          tag: getTag                            # name : method to get the parameter value
#        group_by: { column: tag, method: Tag }   # group by the specified column/method
#        freq:             weekly                 # must be either: always, hourly, daily, weekly, monthly, yearly, never
#        priority:         0.2                    # 1.0 is top priority (100%) compared to 0.2 which is less priority (20%)