generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Event
    theme:                 deneb
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          event
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [=name, publish_state, event_category, start_date, end_date]
      filter:  
        class: false
      form:    ~
      edit:    ~
      new:     ~
