generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Home
    theme:                 deneb
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          home
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:        
      fields:  
        object_name:
          label: Nombre
        type:
          label: Tipo
        position:
          label: Posición
      list:    
        actions: {}
        batch_actions: {}
        object_actions:
          _delete: ~   
          edit: {label: Editar, action: editObject}
        display: [object_name, type, position]
        sort: [position] 
        max_per_page: 0    
      filter:  
        class: false           
      form:    ~
      edit:    ~
      new:     ~
