generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Faq
    theme:                 deneb
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          faq
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        question:
          label: Pregunta
        answer:
          label: Respuesta
      list:
        display: [=question, position]
        sort: [position]
      filter:  
        class: false
      form:    ~
      edit:    ~
      new:     ~
