generator:
  class: sfDoctrineGenerator
  param:
    model_class:           City
    theme:                 deneb
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          city
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [id, state, name, latitude, longitude, altitude]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
