providerSuccess:
  stylesheets:    [main.css,  /sfDoctrineApplyPlugin/css/login-apply]
  javascripts:    [jquery-1.4.3.min.js, jquery-ui-1.8.6.custom.min.js,, /sfDependentSelectPlugin/js/SelectDependiente.min.js,tiny_mce/tiny_mce.js, ]
  
consumerSuccess:
  stylesheets:    [main.css,  /sfDoctrineApplyPlugin/css/login-apply]
  javascripts:    [jquery-1.4.3.min.js, jquery-ui-1.8.6.custom.min.js,, /sfDependentSelectPlugin/js/SelectDependiente.min.js,tiny_mce/tiny_mce.js]

default:
  stylesheets:    [main.css, /sfDoctrineApplyPlugin/css/login-apply,/sfJQueryUIPlugin/css/ui-lightness/jquery-ui.css]    