generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Landing
    theme:                 deneb
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          landing
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        menu_link:
          label: Enlace en el menú
        name: 
          label: Nombre
      list:    
        display: [=name, menu_link]
      filter:  
        class: false
      form:    ~
      edit:    ~
      new:     ~
