generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardPermission
    theme:                 deneb
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_permission
    with_doctrine_route:   true

    config:
      list:
        title: Permission list
        display: [=name, description]
      
      filter: 
        class: false
      
      edit:
        title: Editing Permission "%%name%%"

      new:
        title: New Permission

      form:
        display: [name, description, groups_list, users_list]